name: Posc
version: 1.0
main: io.github.thelordman.posc.Posc
api-version: 1.18
authors: [thelordman, CatalysmRL, TotallyAl, hotpocket184]
description: The main plugin used by Posc. posc.minehut.gg | https://discord.gg/YeUacKAWV2
website: thelordman.github.io
load: POSTWORLD
default-permission: op
depend:
  - FastAsyncWorldEdit
commands:
  gmc:
    description: Changes target's gamemode to creative.
    usage: /gmc [player]
  gms:
    description: Changes target's gamemode to survival.
    usage: /gms [player]
  gma:
    description: Changes target's gamemode to adventure.
    usage: /gma [player]
  gmsp:
    description: Changes target's gamemode to spectator.
    usage: /gmsp [player]
  balance:
    description: Check the balance of an offline or online player.
    aliases: bal
    usage: /bal [player]
  economy:
    description: Change or get various values about the target's economy.
    aliases: [eco, econ]
    usage: /eco <player> <set | add | remove | reset | multiply | divide | get | pow> [<amount>]
  stats:
    description: Check the stats of an offline or online player.
    aliases: st
    usage: /stats [player]
  jail:
    description: Send or release a player to or from jail, or set the location of jail.
    aliases: j
    usage: /jail [player]
  sun:
    description: Set the weather to sunny.
    aliases: [clean, clouds]
    usage: /sun
  rain:
    description: Set the weather to rain.
    aliases: [snow, downfall]
    usage: /rain
  thunder:
    description: Set the weather to thunder.
    aliases: storm
    usage: /thunder
  broadcast:
    description: Send a broadcast accross the server and in Discord.
    aliases: bc
    usage: /broadcast <text>
  spawn:
    description: Send someone or yourself to spawn.
    usage: /spawn [player]
  tphere:
    description: Teleports the target to the location of the executor.
    usage: /tphere <player>
  commandspy:
    description: Toggle Command Spy on and off. While toggled on, you can see all executed commands by everyone.
    aliases: [cmdspy, cspy]
    usage: /commandspy
  rank:
    description: Give any online player any rank.
    usage: /rank <player> set <rank>
  help:
    description: Link to the wiki.
    usage: /help
  discord:
    description: Link to the Discord server.
    aliases: dc
    usage: /discord
  mine:
    description: Reset the mine.
    aliases: m
    usage: /mine
  bounty:
    description: Set or check a player's bounty.
    usage: /bounty [player] [amount]
  stal:
    description: stal
    usage: /stal [player]
  enderchest:
    description: Access your's or someone else's enderchest.
    aliases: ec
    usage: /ec [player]
  donator:
    description: View the permissions and commands of donator ranks.
    aliases: donor
    usage: /donor
  joinkit:
    description: Give an online player the default kit.
    usage: /joinkit [player]
  level:
    description: Change or get various values about the target's level.
    usage: /level <offline-player> <set|add|remove|reset|multiply|divide|get|pow> [<amount>]
  glow:
    description: Add or remove glowing to yourself.
    usage: /glow
  pay:
    description: Send someone a set amount of money from your balance.
    usage: /pay <player> <amount>
  vanish:
    description: Go invisible to all players with a lower rank than you.
    aliases: v
    usage: /vanish [player]
  clearchat:
    description: Clear the chat.
    aliases: cc
    usage: /clearchat
  staffchat:
    description: Send a message that only staff can see. (Also sends a message in Discord staff-chat channel)
    aliases: sc
    usage: /sc <message>
  staffmode:
    description: Become one with the staff...
    aliases: sm
  leaderboard:
    description: Send a message that only staff can see. (Also sends a message in Discord staff-chat channel)
    aliases: [lb, top]
    usage: /lb <bal | level | block | kill | death | kdr | bounty | playtime | killstreak>
  top:
    description: Teleports you to the highest non passable block at your location
    usage: /top [player]
  punishments:
    description: Shows you the punishment history of an offline player or yourself.
    usage: /punishments [player]
  liami:
    description: Send a message as Liami, even when he's offline.
    usage: /liami <message>
  map:
    description: Reset the entire map.
    usage: /map
  sudo:
    description: Send a command or message (c:) as an online player.
    usage: /sudo <player> <command or c:message>
  data:
    description: Modify a player's data.
    usage: /data <player> <statistic | playerdata> <statistic type | playerdata type> <set | add | take | multiply | divide | power | squareroot> <amount>
  mute:
    description: Mute a player.
    usage: /mute <player> [time | perm] [reason] [-s]
  unmute:
    description: Unmute a player.
    usage: /unmute <player> [-s]
  kick:
    description: Kick a player.
    usage: /kick <player> [reason] [-s]
  warn:
    description: Warn a player.
    usage: /warn <player> [reason] [-s]
  ban:
    description: Ban a player.
    usage: /ban <player> [time | perm] [reason] [-s]
  unban:
    description: Ban a player.
    usage: /unban <player> [-s]
  ipban:
    description: Ban the IP address of a player.
    aliases: banip
    usage: /ipban <player> [time | perm] [reason] [-s]
  unipban:
    description: Unban the IP address of a player.
    aliases: unbanip
    usage: /unipban <player> [-s]
  fly:
    description: enables flight for the player
    usage: /fly
  flyspeed:
    description: set fly speed
    usage: /flyspeed <amount>