name: Posc
version: '1.0-INDEV'
main: me.lord.posc.Posc
api-version: 1.19
authors: [Lord, hotpocket, Kiip]
website: https://discord.gg/YeUacKAWV2
commands:
  gmc:
    description: Changes your or an online player's gamemode to creative.
    usage: /gmc [<player>]
  gms:
    description: Changes your or an online player's gamemode to survival.
    usage: /gms [<player>]
  gma:
    description: Changes your or an online player's gamemode to adventure.
    usage: /gma [<player>]
  gmsp:
    description: Changes your or an online player's gamemode to spectator.
    usage: /gmsp [<player>]
  kill:
    description: Kills yourself or an online player.
    usage: /kill [<player>]
    aliases:
      - suicide
  nick:
    description: Nicknames you.
    usage: /nick <text>
  npc:
    description: Command to create and modify NPCs.
    usage: /npc <create | sel | list | delete | rename | move | skin | help> [<text>]
  world:
    description: Command to create and modify Worlds.
    usage: /world <create | list | delete | join> [<name>]
  event:
    description: Join or start an event.
    usage: /event <join | start> [<name>]